casaNipo/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

organizacao/urls.py
from django.contrib import admin
from django.urls import path, include
import organizacao.views as views

app_name = 'organizacao'

urlpatterns = [
    path('', views.core),
    path('atualiza/', views.atualiza_lista, name='atualiza')
]

organizacao/models.py
from django.db import models


# Create your models here.

class Geladeira(models.Model):
    # Limpeza na segunda e quarta semana do mẽs
    SEMANA_CHOICES = [
        (0, 'Segunda'),
        (1, 'Terça'),
        (2, 'Quarta'),
        (3, 'Quinta'),
        (4, 'Sexta'),
        (5, 'Sábado'),
        (6, 'Domingo'),
    ]
    # Dia da semana da limpeza
    numGeladeira = models.IntegerField('Número da Geladeira')
    dia_inicial_limpeza = models.IntegerField(choices=SEMANA_CHOICES)
    dia_final_limpeza = models.IntegerField(choices=SEMANA_CHOICES)

    def __str__(self):
        return "Geladeira" + " " + str(self.numGeladeira)


class MicroEFogao(models.Model):
    # Para casa nipo: Toda semana segunda, quarta e sexta
    SEMANA_CHOICES = [
        (0, 'Segunda'),
        (1, 'Terça'),
        (2, 'Quarta'),
        (3, 'Quinta'),
        (4, 'Sexta'),
        (5, 'Sábado'),
        (6, 'Domingo'),
    ]
    dia_de_limpeza = models.IntegerField(choices=SEMANA_CHOICES)
    dia_de_limpeza1 = models.IntegerField(choices=SEMANA_CHOICES)
    dia_de_limpeza2 = models.IntegerField(choices=SEMANA_CHOICES)

    def __str__(self):
        return "Microondas e Fogão"

    class Meta:
        verbose_name = 'Micro-ondas e Fogão'
        verbose_name_plural = "Micro-ondas e Fogões"


class Pessoas(models.Model):
    nome = models.CharField(max_length=120,
                            help_text='Na inserção de novas pessoas, a prioridade será zero. Caso queira alterar, '
                                      'entre na aba da pessoa e altere o valor manualmente')
    # Com o menor numero de prioridade é quem vai lavar
    prioridadeFogao = models.IntegerField(blank=True, default=0)
    prioridadeGeladeira = models.IntegerField(blank=True, default=0)

    def save(self, *args, **kwargs):
        # Primeira vez
        if not self.pk:
            pessoas = Pessoas.objects.all()
            for pessoa in pessoas:
                pessoa.prioridadeFogao += 1
                pessoa.prioridadeGeladeira += 1
                pessoa.save()
            self.prioridadeGeladeira = 0
            self.prioridadeFogao = 0
            super(Pessoas, self).save(*args, **kwargs)
        else:
            super(Pessoas, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        pessoas = Pessoas.objects.all()
        for pessoa in pessoas:
            if pessoa.prioridadeFogao > self.prioridadeFogao:
                pessoa.prioridadeFogao -= 1
            if pessoa.prioridadeGeladeira > self.prioridadeGeladeira:
                pessoa.prioridadeGeladeira -= 1

            pessoa.save()
        super(Pessoas, self).delete(*args, **kwargs)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Pessoa'
        verbose_name_plural = "Lista de Pessoas"


class TrabalhoGeladeira(models.Model):
    pessoa = models.ForeignKey(Pessoas, on_delete=models.CASCADE)
    geladeira = models.ForeignKey(Geladeira, on_delete=models.CASCADE)
    dia = models.DateField('Dia')
    dia_fim = models.DateField('último dia', default="1999-01-01")

    def __str__(self):
        return str(self.pessoa) + " - " + str(self.geladeira) + " - " + " Dia " + str(self.dia.day)

    class Meta:
        verbose_name = 'Relação de Limpeza da Geladeira'
        verbose_name_plural = "Relação de Limpeza das Geladeiras"


class TrabalhoFogao(models.Model):
    pessoa = models.ForeignKey(Pessoas, on_delete=models.CASCADE)
    fogao = models.ForeignKey(MicroEFogao, on_delete=models.CASCADE)
    dia = models.DateField('Dia')

    def __str__(self):
        return str(self.pessoa) + " - " + str(self.fogao) + " - " + " Dia " + str(self.dia.day)

    class Meta:
        verbose_name = 'Relação de Limpeza do Fogão'
        verbose_name_plural = "Relação de Limpeza dos Fogões"

organizacao/forms.py
from django import forms


class MesForm(forms.Form):
    CHOICES = (
        (1, 'Janeiro'),
        (2, 'Fevereiro'),
        (3, 'Março'),
        (4, 'Abril'),
        (5, 'Maio'),
        (6, 'Junho'),
        (7, 'Julho'),
        (8, 'Agosto'),
        (9, 'Setembro'),
        (10, 'Outubro'),
        (11, 'Novembro'),
        (12, 'Dezembro'),
    )
    field = forms.ChoiceField(label='Mês', widget=forms.Select(attrs={'class': 'selectpicker btn-outline-dark'}),
                              choices=CHOICES)

organizacao/views.py
from django.shortcuts import render
from .models import Geladeira, Pessoas, TrabalhoFogao, TrabalhoGeladeira, MicroEFogao
from Scripts import getDays
from datetime import timedelta
from django.contrib.auth.decorators import login_required
from .forms import MesForm


# Create your views here.

def core(request):
    template_name = 'core.html'
    context = {
        'Geladeira': Geladeira.objects.all(),
        'TrabalhoGeladeira': TrabalhoGeladeira.objects.all(),
        'TrabalhoFogao': TrabalhoFogao.objects.all()
    }

    return render(request, template_name, context)


@login_required
def atualiza_lista(request):
    template_name = 'atualiza.html'
    form = MesForm(request.POST or None)
    context = {}
    # Se o forms for válido
    if form.is_valid():
        # Coleta a opção
        mes = form.cleaned_data.get('field')
        mes = int(mes)
        # Mostra somente daquele tipo especifico
        c = getDays.calendar.Calendar(0)
        data_atual = getDays.date.today()
        mes_aux = c.monthdays2calendar(data_atual.year, mes)
        trabalho_no_mes = TrabalhoFogao.objects.filter(dia__month=mes)
        if len(trabalho_no_mes) > 0:
            context["Erro"] = "Já foi atualizada a lista deste mês!"
        else:
            lavaGeladeira(mes_aux, mes)
            lavaFogao(mes_aux, mes)
            context["Sucesso"] = "A lista do mês foi atualizada!"
    context["form"] = form
    return render(request, template_name, context)


def lavaGeladeira(semana, mes):
    quantidadeGeladeira = Geladeira.objects.count()
    geladeiras = Geladeira.objects.all()
    segundaSemana, quartaSemana = getDays.diasGeladeira(semana,mes)  # Lista com os dias de trabalho
    quantidadePessoas = (quantidadeGeladeira * 2)
    listpessoasTrabalho = Pessoas.objects.order_by('prioridadeGeladeira')[:quantidadePessoas]
    listpessoasnaoTrabalho = Pessoas.objects.order_by('prioridadeGeladeira')[quantidadePessoas:]
    pessoasTotal = (len(listpessoasTrabalho) + len(listpessoasnaoTrabalho))
    for idx, pessoa in enumerate(listpessoasTrabalho):
        # Das pessoas que trabalharem, iremos aumentar sua prioridade
        # Aumento proporcional ao número de pessoas
        pessoa.prioridadeGeladeira += (pessoasTotal - quantidadePessoas)
        pessoa.save()
        if idx < (quantidadePessoas / 2):
            TrabalhoGeladeira.objects.create(pessoa=pessoa, geladeira=geladeiras[idx % quantidadeGeladeira],
                                             dia=segundaSemana[0], dia_fim=segundaSemana[3] + timedelta(days=1))
        else:
            TrabalhoGeladeira.objects.create(pessoa=pessoa, geladeira=geladeiras[idx % quantidadeGeladeira],
                                             dia=quartaSemana[0], dia_fim=quartaSemana[3] + timedelta(days=1))
    for pessoa in listpessoasnaoTrabalho:
        print(pessoa)
        # Das pessoas que seguem a lista iremos subtrair a quantidade de pessoas que trabalharam
        pessoa.prioridadeGeladeira -= quantidadePessoas
        pessoa.save()


def lavaFogao(semana, mes):
    quantidadeFogao = MicroEFogao.objects.count()
    fogoeos = MicroEFogao.objects.all()
    segundas, quartas, sextas = getDays.diasFogaoMicroondas(semana, mes)
    diaLimpeza = segundas + quartas + sextas
    quantidadePessoas = (len(segundas) + len(quartas) + len(sextas)) * quantidadeFogao
    listPessoastrabalho = Pessoas.objects.order_by('prioridadeFogao')[:quantidadePessoas]
    listpessoasnaoTrabalho = Pessoas.objects.order_by('prioridadeFogao')[quantidadePessoas:]
    pessoasTotal = (len(listPessoastrabalho) + len(listpessoasnaoTrabalho))
    for idx, pessoa in enumerate(listPessoastrabalho):
        # Das pessoas que trabalharem, iremos aumentar sua prioridade
        # Aumento proporcional ao número de pessoas
        pessoa.prioridadeFogao += (pessoasTotal - quantidadePessoas)
        pessoa.save()
        TrabalhoFogao.objects.create(pessoa=pessoa, fogao=fogoeos[idx % quantidadeFogao],
                                     dia=diaLimpeza[idx])
    for pessoa in listpessoasnaoTrabalho:
        print(pessoa)
        # Das pessoas que seguem a lista iremos subtrair a quantidade de pessoas que trabalharam
        pessoa.prioridadeFogao -= quantidadePessoas
        pessoa.save()

organizacao/templates/atualiza.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Seleção do Mês</title>
</head>
<body>

<h1> {{ Sucesso }}</h1>
<h1> {{ Erro }}</h1>
<form action="{% url 'organizacao:atualiza' %}" method=POST>
    {% csrf_token %}
    <h3>Escolha o mês que será atualizado:</h3>
    <div class="text-center"> {{ form }} <input class="btn btn-outline-dark" type="submit" value="Atualizar"
                                                onmouseover="this.style.backgroundColor='#02801b', this.style.color='#f8fff9'"
                                                onmouseout="this.style.backgroundColor='', this.style.color=''">
    </div>
</form>

</body>
</html>

organizacao/templates/core.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Casa Nipo</title>

    <!-- Full Callendar -->
    <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.css"/>

    <!-- Font Awesome -->
    <script crossorigin="anonymous" defer
            integrity="sha384-DJ25uNYET2XCl5ZF++U8eNxPWqcKohUUBUpKGlNLMchM7q4Wjg2CUpjHLaL8yYPH"
            src="https://use.fontawesome.com/releases/v5.8.2/js/all.js"></script>

    <!-- Bootstrap -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://momentjs.com/downloads/moment.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/locale/pt-br.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js'></script>
    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js'></script>
</head>
<body>
<div class="container">
    <div class="jumbotron">
        <h1 class="text-center">Calendário de Limpeza</h1>
        <script>
            $(function () {
                $('#calendar').fullCalendar({
                    plugins: ['interaction', 'dayGrid', 'timeGrid', 'list'],
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        // dayGridMonth, timeGridMonth, timeGridDay not workings
                        right: 'dayGridMonth, timeGridMonth, timeGridDay, month , listMonth'
                    },
                    buttonIcons: false,
                    navLinks: true,
                    eventLimit: true,
                    locale: 'pt-br',
                    eventRender: function (trabObj, $el) {
                        // Analisando se o evento é o dia inteiro para modificar layout do hover
                        var conteudo;
                        conteudo = '<div>' + trabObj.title + '</div>' +
                            '<i class="fas fa-map-marker-alt"></i>' + ' ' + trabObj.nome + '</div>';


                        $el.popover({
                            title: trabObj.title,
                            html: true,
                            content: conteudo,
                            trigger:
                                'hover',
                            placement:
                                'top',
                            container:
                                'body'
                        })
                        ;

                    },
                    events: [
                        {% for trabalho in TrabalhoGeladeira %}
                            {
                                id: '{{ trabalho.id }}',
                                title: '{{ trabalho.pessoa.nome }}',
                                start: '{{ trabalho.dia|date:'Y-m-d' }}',
                                end: '{{ trabalho.dia_fim|date:'Y-m-d' }}',
                                nome: 'Geladeira {{  trabalho.geladeira.numGeladeira }}',
                                backgroundColor: '#001652',
                                borderColor: '#001652',
                                textColor: 'white',
                            },
                        {% endfor %}

                        {% for trabalho in TrabalhoFogao %}
                            {
                                id: '{{ trabalho.id }}',
                                title: '{{ trabalho.pessoa.nome }}',
                                start: '{{ trabalho.dia|date:'Y-m-d' }}',
                                end: '{{ trabalho.dia|date:'Y-m-d' }}',
                                nome: 'Fogão e Micro-ondas',
                                start_time: '00:00',
                                end_time: '23:59',
                                backgroundColor: '#ff0300',
                                borderColor: '#001652',
                                textColor: 'white',
                            },
                        {% endfor %}
                    ]
                });
            });
        </script>
        <br>
        <div id='calendar'></div>
    </div>
</div>

</body>
</html>